# Generated by Django 2.2 on 2019-08-08 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('Nom_Redion', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Non de region')),
                ('vpen', models.CharField(max_length=50, verbose_name='VPEN')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('Nom_Zone', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Non de zone')),
                ('vpn_a', models.CharField(max_length=50, verbose_name='VPN A')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OLM.Region')),
            ],
        ),
        migrations.CreateModel(
            name='OLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olm', models.CharField(max_length=50, verbose_name='OLM')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OLM.Zone')),
            ],
            options={
                'db_table': 'OLM',
            },
        ),
    ]
