# Generated by Django 2.2 on 2019-08-08 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dat_pc',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 8, 8, 18, 25, 26, 225293), verbose_name='Date de Prise de contact'),
        ),
    ]
