# Generated by Django 2.2 on 2019-09-09 21:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190904_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dat_pc',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 9, 9, 21, 10, 42, 614170, tzinfo=utc), null=True, verbose_name='Date de Prise de contact'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publications',
            name='pub_file',
            field=models.FileField(blank=True, null=True, upload_to=profiles.models.publication, verbose_name='Choisir une image'),
        ),
    ]
