# Generated by Django 2.2 on 2019-08-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=50, verbose_name='Institution')),
                ('respo', models.CharField(max_length=50, verbose_name='Responsable')),
            ],
            options={
                'db_table': 'Institutions',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axe', models.TextField(verbose_name='Axe')),
            ],
            options={
                'db_table': 'Plan_stratégique',
            },
        ),
    ]
