# Generated by Django 2.2 on 2019-09-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activites', '0002_auto_20190904_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activites',
            name='img',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
