# Generated by Django 2.2 on 2019-08-10 19:42

import actualites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actu_titre', models.CharField(blank=True, max_length=256, null=True, verbose_name='Titre')),
                ('actu_img', models.ImageField(blank=True, null=True, upload_to=actualites.models.Actu, verbose_name='Image')),
                ('actu_descri', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('actu_dat', models.DateTimeField(auto_now=True, verbose_name='Date de publication')),
            ],
            options={
                'db_table': 'Actualites',
            },
        ),
    ]
